module.exports = {
    FB_PAGE_TOKEN: process.env.FB_PAGE_TOKEN,
    FB_VERIFY_TOKEN: process.env.FB_VERIFY_TOKEN,
    FB_APP_SECRET: process.env.FB_APP_SECRET,
    SERVER_URL: process.env.SERVER_URL,
    GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
    DF_LANGUAGE_CODE: process.env.DF_LANGUAGE_CODE,
    GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
    GOOGLE_PRIVATE_KEY: JSON.parse(`${process.env.GOOGLE_PRIVATE_KEY}`),
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    EMAIL_FROM: process.env.EMAIL_FROM,
    EMAIL_TO: process.env.EMAIL_TO,
    SENDGRID_PASSWORD: process.env.SENDGRID_PASSWORD,
    SENDGRID_USERNAME: process.env.SENDGRID_USERNAME
};


-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSeaKRtFGoPou8\\nOWtqaOSrSvtiJUcc52O2Z9sv9yrgmm2aR27I305VSNjbAzdax6uK4M4SiqRAHFzp\\nFVFzDFVXw61+iLw1zyyBppZ4CES+hwYZjrv8Sp97be/rP9WOftf3u1Px0oAcfRC7\\nBK8RlI/otkoE8WO20YjS9HibZumOVRAweb6gUrxGPuMrmVRQM9fG0AJEL9GCeQGi\\nh7se/KFbsn/uay+otriRt/dxERaxYzoynl0L0WaJHKRtrGhDWQgSuU4/GQdumsDu\\n92NutnzeXx1qhpx62SrOX+XmaL43IdQdodsO3iJf5oW7gjYJc70g0dE94dWQ/BBh\\nYC+3XPR9AgMBAAECggEACpi0HhjReaJ4f4f2h/ty88rJIDZXP7XIl+DfsKkFgBxW\\nQ0uwYK2ZcILD5DbjvQ7LbKkHxvgy78VdyiBYIu4uh8YiwHma3CyrhXWBItbruxnq\\nLTQ586hAIkM1LodetZdeQSstvUGHUKfdRUUlmUF9A07WKCyNBCHFfTVwswY54QAA\\n+cYjmnLohdnDZAR/lZsylUbzzw7/TyH8hdYiZ0FRc4/AUv2OCe4hYU7Tk8+Z2xOo\\n18ztdE5n5An3MIKrfoXGbO7fxZruhHFszWlP1YfyGXWiY421ofDUqVSTbl4ZVhha\\nOUAWucRyijaDlSCA3bavhPG39ZmN+zbYN66nsIu2gwKBgQDsCer5ICyXaiSvoh6Z\\nI/htAU+QGqP6sV1TL5C9zag0lpjdwhocZiwrISf57J8X09IKy9LV/7WVBEbdip3C\\nVRr61IiLhnKf1yD1UNHOX8rx1sQK1Bs4KW9D5FAysxOL8u9Qcfz7/LEi1TpmWnto\\n0ynew7CiUhgQHo0SU+LC7NyCSwKBgQDkRkg3FPYAzN981d94emseY3eYI/mY0Hbp\\ni7P5XoqQn+uEPo8kmhXqFX9bT1yRh+jJpgvxtkTY0P+UL3P6Iw7/uf80gUaJKHPX\\nRMHTEBnaSu7+ycZZSffXJss/XeMge9oKMwKPZlhEqON1VcUL9qmrzjHpLxgg3O+Z\\nV46e27HnVwKBgQDc7SeGiEvUaR/vWCGlmtpiRLDQo27KLYq5WrLyRHTky/RG0++W\\nlzdOIxmEvqnmJnfZbQ9pB49Q7BDcOWsRwpCfJ6CqX2wYGcaadkv6CwUsOKWDsSXM\\n+lNPS3qZCa4I9phyRk7RGKI/hS7FMHmEEumEvMsuEwK8y6uk9OkxI3v9YwKBgQCH\\nKq6cHwdDlgxHiQSX/DTte4xXRAYJXHbs91IMONTnqin01m5ACBUt1Kji0m1HpyhK\\nLs4nw/ukPqz3e9m6pYO+HM5msp2nnZJqR0ZVydTlEzXNHIEcYdYlSc1Tqi5RD8Ue\\nAPJlIv7lOPPmiHDzEo2JM8EOCFrLKsedDuFeY0xGZQKBgH2CEcgGMxFjj381LKOf\\nJGLDNikCYJ4a4RkcipHgsn9HfCpYJdEFQMWjS4+BKiPzhWG36HqHkScqoLRFLHb8\\nl43+RajMau6jLxYfITcyx5tUv3q/r4Ndn/X23GeJTf0Kz7iXuYZ4fbxfY1BcIXl9\\nrvLyYaGtMdirwJnwInfH+OFK\\n-----END PRIVATE KEY-----\\n