module.exports = {
    FB_PAGE_TOKEN: 'EAAMlgK43XeABAJEQINoxce07xm5bxq8kZAxNQDG2weyIeZBBdwJJ5zodZBJ9UqZCYkI608tSpZBiiOZCBygPZAOZBQ601DFtwSfadji90XYQwBsf9gxJrd0nmXWZAPyygv6vxXlgAWdtD9vxKHu057ggzNbxC5PZAFT2hYai1cO890Fkd1UZAn2FxET',
    FB_VERIFY_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: '',
    GOOGLE_PROJECT_ID: '',
    DF_LANGUAGE_CODE: '',
    GOOGLE_CLIENT_EMAIL: '',
    GOOGLE_PRIVATE_KEY: ''
};